name: Deploy to PreProd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, tenant1]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Pre-Prod Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TEST_USERNAME }}@${{ secrets.TEST_HOST }} powershell.exe -Command "cd C:\\inetpub\\wwwroot; git clone https://github.com/ZaurTestLLC/emil.git;"
